update =(actualizar)
SET =(conjunto)
from=(desde)
where =(donde)
select=(seleccionar)
from=(desde)
select*from(seleccione desde)
insert into=(inserte en)
values =(valores)
delete from =(eliminar desde)
create table =(crear tabla)
not null =(no nulo)
varchar =(almacen de series de caracteristica)
primary key =(llave primaria)
id =(identificador)
create table =(crear tabla)
select * from =(seleccione desde)
delete from =(elimina desde)
